# st-gcn/config/st_gcn/mediapipe-asl.yaml

work_dir: ./work_dir/mediapipe_asl/

model_saved_name: ./runs/mediapipe_asl

phase: train
device: [0]
num_epoch: 80
train_batch_size: 8
test_batch_size: 8

model: model.st_gcn.Model
model_args:
  in_channels: 6 # 3 original + 3 velocity
  num_class: 90 # ✅ Replace this with your actual class count
  num_point: 21
  num_person: 1
  graph: graph.mediapipe_asl.Graph
  graph_args:
    layout: "mediapipe_asl"
    strategy: "spatial"
weights: ./weights/epoch380_model.pt
train_feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/mediapipe_asl/train_data.npy
  label_path: ./data/mediapipe_asl/train_label.pkl
  debug: False

test_feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/mediapipe_asl/val_data.npy
  label_path: ./data/mediapipe_asl/val_label.pkl
